# Generated by Django 4.2.11 on 2024-05-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='Word(en)')),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.direction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UzbekWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uzWord', models.CharField(max_length=50, verbose_name='Word(uz)')),
                ('enWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.englishword')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
